name: folder1 deploy
on:
   workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true
   workflow_dispatch:
    inputs:
      environment:
        description: 'ENV'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - uat


jobs:
  folder1_deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ./folder1
    steps:
      - name: Checkout current GitHub Actions workflow repository
        uses: actions/checkout@v3
      - id: Folder1-Deploy
        env:
         RUNNERS: ${{ format('[self-hosted, aws-{0}]', inputs.environment) }}
        run: echo "$RUNNERS" && pwd && ls -la
      - id: Folder1
        run: cd ~ && pwd && ls -la
