name: Folder2 deploy
on:
   workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true
      masking:
        type: boolean
        description: Trigger to run masking policies jobs
        required: false

jobs:
  snowflow:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-labs/dbt-snowflake:1.6.0
    environment: ${{ inputs.environment}}
    steps:
      - id: Folder2-Deploy
        env:
         RUNNERS: ${{ format('[self-hosted, aws-{0}]', inputs.environment) }}
        run: echo "$RUNNERS" && ps aux
      - id: dbt-Deploy
        run: dbt -h

