# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Calculator
on:
  push:
    branches: [dev, main, prod]
  pull_request:
    branches: [dev, main, prod]


jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_runners_and_environment.outputs.environment }}
    steps:
      - name: Checkout current GitHub Actions workflow repository
        uses: actions/checkout@v3

      - name: Setup runners and Environment
        id: set_runners_and_environment
        run: |
          TARGET_BRANCH=${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name}}
          if [ "$TARGET_BRANCH" = "main" ]; then
            ENVIRONMENT="uat"
          else
            ENVIRONMENT="${TARGET_BRANCH}"
          fi
          echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT
          
  terraform:
    uses: ./.github/workflows/test_dynamic_env.yaml
    with:
      environment: ${{ needs.prepare.outputs.environment }}
    secrets: inherit
