name: test dynamic envs
on:
  pull_request:
    branches: [dev, main, prod]


jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref == 'main' && 'uat' || github.base_ref }}
    env:
      test_env: alalalala
    steps:
      - id: set_environment
        run: echo $test_env
