name: test dynamic envs
on:
   workflow_call:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - id: set_environment
        run: echo ${{ github.event_name }}
      - id: set
        run: echo ${{ github.event }}
