name: test dynamic envs
on:
   workflow_call:

jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: 'dev'
    steps:
      - id: set_environment
        env:
         GITHUB_EVENT_NAME: ${{ toJson(github.event_name) }}
        run: echo "$GITHUB_EVENT_NAME"
      - id: set
        env:
         GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - id: setaaa
        run: echo ${{ jobs.prepare.environment }}
