name: test dynamic envs
on:
   workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true
      masking:
        type: boolean
        description: Trigger to run masking policies jobs
        required: false
   workflow_dispatch:
    inputs:
      environment:
        description: 'ENV'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - uat

concurrency:
  group: uat_env

jobs:
  linting:
    runs-on: ubuntu-latest
    if: ${{ inputs.masking }}
    steps:
      - name: Checkout current GitHub Actions workflow repository
        uses: actions/checkout@v3
      - id: lint
        run: echo "Linting"
  testing:
    if: ${{ !inputs.masking }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current GitHub Actions workflow repository
        uses: actions/checkout@v3
      - id: lint
        run: echo "Testing"
 
  prepare:
    runs-on: ubuntu-latest
    needs: [linting]
    if: ${{ success() }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout current GitHub Actions workflow repository
        uses: actions/checkout@v3
      - id: read_file
        run: cat test
      - id: set
        env:
         GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - id: setaaa
        run: echo ${{ vars.TEST_VAR }}
      - id: setbbbbb
        env:
         RUNNERS: ${{ format('[self-hosted, aws-{0}]', inputs.environment) }}
        run: echo "$RUNNERS"
