name: test needs in matrix
on:
   workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true
      masking:
        type: boolean
        description: Trigger to run masking policies jobs
        required: false

jobs:
  linting:
    runs-on: ubuntu-latest
    if: ${{ inputs.masking }}
    steps:
      - name: Checkout current GitHub Actions workflow repository
        uses: actions/checkout@v3
      - id: lint
        run: echo "Linting"
 
  snowflow:
    runs-on: ubuntu-latest
    needs: [linting]
    if: ${{ success() }}
    environment: ${{ inputs.environment}}
    steps:
      - id: set_environment
        env:
         GITHUB_EVENT_NAME: ${{ toJson(github.event_name) }}
        run: echo "$GITHUB_EVENT_NAME"
      - id: set
        env:
         GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - id: setaaa
        run: echo ${{ vars.TEST_VAR }}
      - id: setbbbbb
        env:
         RUNNERS: ${{ format('[self-hosted, aws-{0}]', inputs.environment) }}
        run: echo "$RUNNERS"
