name: test dynamic envs
on:
   workflow_call:
   workflow_dispatch:
    inputs:
      environment:
        description: 'ENV'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - uat

jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'uat' }}
    steps:
      - id: set_environment
        env:
         GITHUB_EVENT_NAME: ${{ toJson(github.event_name) }}
        run: echo "$GITHUB_EVENT_NAME"
      - id: set
        env:
         GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - id: setaaa
        run: echo ${{ vars.TEST_VAR }}
